version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_procrastinapp
    environment:
      MYSQL_ROOT_PASSWORD: MDP
      MYSQL_DATABASE: procrastinApp
      MYSQL_USER: user
      MYSQL_PASSWORD: MDP
      TZ: Europe/Paris
    ports:
      - "3306:3306"
    volumes:
      - mysql_data_procrastinapp:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped

volumes:
  mysql_data_procrastinapp:
