#
# Utilisateur
#

### Utilisateur - Création PROCRASTINATEUR_EN_HERBE
POST http://localhost:9000/api/utilisateurs
Content-Type: application/json

{ "pseudo": "nextchampion", "adresseMail": "newbie@example.com", "role": "PROCRASTINATEUR_EN_HERBE",
  "niveauProcrastination": "DEBUTANT", "excusePreferee": "pourquoi faire ?", "pointAccumules": 0 }

### Utilisateur - Création ANTI_PROCRASTINATEUR_REPENTIS (par GESTIONNAIRE_TEMPS_PERDU)
POST http://localhost:9000/api/utilisateurs/Anti_procrastinateurRepentis
Content-Type: application/json
X-User-Email: gestionnaire@example.com

{ "pseudo": "goat", "adresseMail": "thebest@example.com", "role": "ANTI_PROCRASTINATEUR_REPENTIS",
  "niveauProcrastination": "EXPERT", "excusePreferee": "laissez moi tranquille", "pointAccumules": 1000 }

### Utilisateur - Get all (par GESTIONNAIRE_TEMPS_PERDU)
GET http://localhost:9000/api/utilisateurs
Content-Type: application/json
X-User-Email: gestionnaire@example.com

### Utilisateur - Get by Id (par GESTIONNAIRE_TEMPS_PERDU)
GET http://localhost:9000/api/utilisateurs/1
Content-Type: application/json
X-User-Email: gestionnaire@example.com

### Utilisateur - Modification (par GESTIONNAIRE_TEMPS_PERDU)
PUT http://localhost:9000/api/utilisateurs/3
Content-Type: application/json
X-User-Email: gestionnaire@example.com

{
  "pseudo": "goat",
  "adresseMail": "thebest@example.com",
  "niveauProcrastination": "EXPERT",
  "excusePreferee": "j'ai changé !",
  "pointAccumules": 1200
}


### Utilisateur - Supression (par GESTIONNAIRE_TEMPS_PERDU)
DELETE http://localhost:9000/api/utilisateurs/2
Content-Type: application/json
X-User-Email: gestionnaire@example.com

#
# Connexion
#

### Connexion - Connexion
POST http://localhost:9000/api/connexion
Content-Type: application/json
X-User-Email: gestionnaire@example.com


#
# PiegeProductivite
#

### PiegeProductivite - Créer un piège de productivité (par ANTI_PROCRASTINATEUR_REPENTIS)
POST http://localhost:9000/api/pieges-productivite
Content-Type: application/json
X-User-Email: thebest@example.com

{
  "titre": "Défilement infini sur TikTok",
  "description": "Tu ouvres l’appli, et soudain 2 heures ont passé.",
  "type": "JEU",
  "niveauDifficulte": 4,
  "recompenseResistance": 50,
  "consequenceEchec": -30
}

### PiegeProductivite - Récupérer des pièges (par ANTI_PROCRASTINATEUR_REPENTIS)
GET http://localhost:9000/api/pieges-productivite
Content-Type: application/json
X-User-Email: thebest@example.com

### PiegeProductivite - Récupérer des pièges par Utilisateur (par ANTI_PROCRASTINATEUR_REPENTIS)
GET http://localhost:9000/api/pieges-productivite/user
Content-Type: application/json
X-User-Email: thebest@example.com

### PiegeProductivite - Récupérer un piège par ID (par ANTI_PROCRASTINATEUR_REPENTIS)
GET http://localhost:9000/api/pieges-productivite/2
Content-Type: application/json
X-User-Email: thebest@example.com


### PiegeProductivite - Modifier un piège existant (par ANTI_PROCRASTINATEUR_REPENTIS)
PUT http://localhost:9000/api/pieges-productivite/1
Content-Type: application/json
X-User-Email: thebest@example.com

{
  "titre": "Scroll de nuit sur Instagram",
  "description": "Il est 1h du matin et tu regardes encore des chats.",
  "type": "JEU",
  "niveauDifficulte": 5,
  "recompenseResistance": 70,
  "consequenceEchec": -40
}

### PiegeProductivite - Suppression d'un piège par ID (par ANTI_PROCRASTINATEUR_REPENTIS)
DELETE http://localhost:9000/api/pieges-productivite/2
Content-Type: application/json
X-User-Email: thebest@example.com

#
# DefiProcrastination
#

### DefiProcrastination - Création (par GESTIONNAIRE_TEMPS_PERDU)
POST http://localhost:9000/api/defis
Content-Type: application/json
X-User-Email: gestionnaire@example.com

{ "titre": "Defi impossible", "description": "Ne fais rien pendant 3 jours", "duree": 3, "difficulte": "DIFFICILE",
  "pointsAGagner": 70, "dateDebut": "2025-01-01", "dateFin": "2025-07-01" }


### DefiProcrastination - Modification (par GESTIONNAIRE_TEMPS_PERDU)
PUT http://localhost:9000/api/defis/1
Content-Type: application/json
X-User-Email: gestionnaire@example.com

{ "id": 1, "titre": "Nouveau titre", "description": "Nouvelle description", "duree": 4, "difficulte": "MOYEN",
  "pointsAGagner": 50, "dateDebut": "2025-06-01", "dateFin": "2025-07-31" }


### DefiProcrastination - Modification statut (par GESTIONNAIRE_TEMPS_PERDU)
PUT http://localhost:9000/api/defis/statut
Content-Type: application/json
X-User-Email: gestionnaire@example.com

{ "id": 1, "actif": false }


### DefiProcrastination - Suppression (par GESTIONNAIRE_TEMPS_PERDU)
DELETE http://localhost:9000/api/defis/1
Content-Type: application/json
X-User-Email: gestionnaire@example.com


#
# ParticipationDefi
#

### ParticipationDefi - Création (par PROCRASTINATEUR_EN_HERBE)
POST http://localhost:9000/api/participations-defis
Content-Type: application/json
X-User-Email: newbie@example.com

{ "defi": {"id": 1} }


### ParticipationDefi - Démarrage si date atteinte (par GESTIONNAIRE_TEMPS_PERDU)
PUT http://localhost:9000/api/participations-defis/commencer
Content-Type: application/json
X-User-Email: gestionnaire@example.com


### ParticipationDefi - Fin (par PROCRASTINATEUR_EN_HERBE)
PUT http://localhost:9000/api/participations-defis
Content-Type: application/json
X-User-Email: newbie@example.com

{ "id": 1, "pointsGagnes": 40 }




### DefiProcrastination - Get all
GET http://localhost:9000/api/defis
Content-Type: application/json
X-User-Email: newbie@example.com

### DefiProcrastination - Get all actifs
GET http://localhost:9000/api/defis/actifs
Content-Type: application/json
X-User-Email: newbie@example.com

### DefiProcrastination - Get by id
GET http://localhost:9000/api/defis/1
Content-Type: application/json
X-User-Email: newbie@example.com


### ParticipationDefi - Get all
GET http://localhost:9000/api/participations-defis
Content-Type: application/json
X-User-Email: gestionnaire@example.com

### ParticipationDefi - Get all by utilisateur connecté
GET http://localhost:9000/api/participations-defis/user
Content-Type: application/json
X-User-Email: newbie@example.com

### ParticipationDefi - Get all by defi
GET http://localhost:9000/api/participations-defis/defi/1
Content-Type: application/json
X-User-Email: gestionnaire@example.com

### ParticipationDefi - Get by id
GET http://localhost:9000/api/participations-defis/1
Content-Type: application/json
X-User-Email: newbie@example.com
