#
# Utilisateur
#

### Utilisateur - Création PROCRASTINATEUR_EN_HERBE
POST http://localhost:9000/api/utilisateurs
Content-Type: application/json

{ "pseudo": "nextchampion", "adresseMail": "newbie@example.com", "role": "PROCRASTINATEUR_EN_HERBE",
  "niveauProcrastination": "DEBUTANT", "excusePreferee": "pourquoi faire ?", "pointAccumules": 0 }

### Utilisateur - Création ANTI_PROCRASTINATEUR_REPENTIS (par GESTIONNAIRE_TEMPS_PERDU)
POST http://localhost:9000/api/utilisateurs/Anti_procrastinateurRepentis
Content-Type: application/json
X-User-Email: gestionnaire@example.com

{ "pseudo": "goat", "adresseMail": "thebest@example.com", "role": "ANTI_PROCRASTINATEUR_REPENTIS",
  "niveauProcrastination": "EXPERT", "excusePreferee": "laissez moi tranquille", "pointAccumules": 1000 }

### Utilisateur - Get all (par GESTIONNAIRE_TEMPS_PERDU)
GET http://localhost:9000/api/utilisateurs
Content-Type: application/json
X-User-Email: gestionnaire@example.com

### Utilisateur - Get by Id (par GESTIONNAIRE_TEMPS_PERDU)
GET http://localhost:9000/api/utilisateurs/1
Content-Type: application/json
X-User-Email: gestionnaire@example.com

### Utilisateur - Modification (par GESTIONNAIRE_TEMPS_PERDU)
PUT http://localhost:9000/api/utilisateurs/3
Content-Type: application/json
X-User-Email: gestionnaire@example.com

{
  "pseudo": "goat",
  "adresseMail": "thebest@example.com",
  "niveauProcrastination": "EXPERT",
  "excusePreferee": "j'ai changé !",
  "pointAccumules": 1200
}


### Utilisateur - Supression (par GESTIONNAIRE_TEMPS_PERDU)
DELETE http://localhost:9000/api/utilisateurs/2
Content-Type: application/json
X-User-Email: gestionnaire@example.com

#
# Connexion
#

### Connexion - Connexion
POST http://localhost:9000/api/connexion
Content-Type: application/json
X-User-Email: gestionnaire@example.com


#
# PiegeProductivite
#

### PiegeProductivite - Créer un piège de productivité (par ANTI_PROCRASTINATEUR_REPENTIS)
POST http://localhost:9000/api/pieges-productivite
Content-Type: application/json
X-User-Email: thebest@example.com

{
  "titre": "Défilement infini sur TikTok",
  "description": "Tu ouvres l’appli, et soudain 2 heures ont passé.",
  "type": "JEU",
  "niveauDifficulte": 4,
  "recompenseResistance": 50,
  "consequenceEchec": -30
}

### PiegeProductivite - Récupérer des pièges (par ANTI_PROCRASTINATEUR_REPENTIS)
GET http://localhost:9000/api/pieges-productivite
Content-Type: application/json
X-User-Email: thebest@example.com

### PiegeProductivite - Récupérer des pièges par Utilisateur (par ANTI_PROCRASTINATEUR_REPENTIS)
GET http://localhost:9000/api/pieges-productivite/user
Content-Type: application/json
X-User-Email: thebest@example.com

### PiegeProductivite - Récupérer un piège par ID (par ANTI_PROCRASTINATEUR_REPENTIS)
GET http://localhost:9000/api/pieges-productivite/2
Content-Type: application/json
X-User-Email: thebest@example.com


### PiegeProductivite - Modifier un piège existant (par ANTI_PROCRASTINATEUR_REPENTIS)
PUT http://localhost:9000/api/pieges-productivite/1
Content-Type: application/json
X-User-Email: thebest@example.com

{
  "titre": "Scroll de nuit sur Instagram",
  "description": "Il est 1h du matin et tu regardes encore des chats.",
  "type": "JEU",
  "niveauDifficulte": 5,
  "recompenseResistance": 70,
  "consequenceEchec": -40
}

### PiegeProductivite - Suppression d'un piège par ID (par ANTI_PROCRASTINATEUR_REPENTIS)
DELETE http://localhost:9000/api/pieges-productivite/2
Content-Type: application/json
X-User-Email: thebest@example.com

#
# DefiProcrastination
#

### DefiProcrastination - Création (par GESTIONNAIRE_TEMPS_PERDU)
POST http://localhost:9000/api/defis
Content-Type: application/json
X-User-Email: gestionnaire@example.com

{ "titre": "Defi impossible", "description": "Ne fais rien pendant 3 jours", "duree": 3, "difficulte": "DIFFICILE",
  "pointsAGagner": 70, "dateDebut": "2025-01-01", "dateFin": "2025-07-01" }

### DefiProcrastination - Get all
GET http://localhost:9000/api/defis
Content-Type: application/json
X-User-Email: newbie@example.com

### DefiProcrastination - Get all actifs
GET http://localhost:9000/api/defis/actifs
Content-Type: application/json
X-User-Email: newbie@example.com

### DefiProcrastination - Get by id
GET http://localhost:9000/api/defis/1
Content-Type: application/json
X-User-Email: newbie@example.com

### DefiProcrastination - Modification (par GESTIONNAIRE_TEMPS_PERDU)
PUT http://localhost:9000/api/defis/1
Content-Type: application/json
X-User-Email: gestionnaire@example.com

{ "id": 1, "titre": "Nouveau titre", "description": "Nouvelle description", "duree": 4, "difficulte": "MOYEN",
  "pointsAGagner": 50, "dateDebut": "2025-06-01", "dateFin": "2025-07-31" }


### DefiProcrastination - Modification statut (par GESTIONNAIRE_TEMPS_PERDU)
PUT http://localhost:9000/api/defis/statut
Content-Type: application/json
X-User-Email: gestionnaire@example.com

{ "id": 1, "actif": false }


### DefiProcrastination - Suppression (par GESTIONNAIRE_TEMPS_PERDU)
DELETE http://localhost:9000/api/defis/1
Content-Type: application/json
X-User-Email: gestionnaire@example.com


#
# ParticipationDefi
#

### ParticipationDefi - Création (par PROCRASTINATEUR_EN_HERBE)
POST http://localhost:9000/api/participations-defis
Content-Type: application/json
X-User-Email: newbie@example.com

{ "defi": {"id": 1} }

### ParticipationDefi - Get all
GET http://localhost:9000/api/participations-defis
Content-Type: application/json
X-User-Email: gestionnaire@example.com

### ParticipationDefi - Get all by utilisateur connecté
GET http://localhost:9000/api/participations-defis/user
Content-Type: application/json
X-User-Email: newbie@example.com

### ParticipationDefi - Get all by defi
GET http://localhost:9000/api/participations-defis/defi/1
Content-Type: application/json
X-User-Email: gestionnaire@example.com

### ParticipationDefi - Get by id
GET http://localhost:9000/api/participations-defis/1
Content-Type: application/json
X-User-Email: newbie@example.com

### ParticipationDefi - Fin (par PROCRASTINATEUR_EN_HERBE)
PUT http://localhost:9000/api/participations-defis
Content-Type: application/json
X-User-Email: newbie@example.com

{ "id": 1, "pointsGagnes": 40 }

### ParticipationDefi - Démarrage si date atteinte (par GESTIONNAIRE_TEMPS_PERDU)
PUT http://localhost:9000/api/participations-defis/commencer
Content-Type: application/json
X-User-Email: gestionnaire@example.com

#
# ExcuseCreative
#

### ExcuseCreative - Création (par PROCRASTINATEUR_EN_HERBE)
POST http://localhost:9000/api/excuse-creative
Content-Type: application/json
X-User-Email: newbie@example.com

{
  "texteExcuse": "Je dois faire une pause pour regarder des vidéos de chiens",
  "situationApp": "le matin avant de commencer le travail",
  "votesRecus": 0,
  "dateSoumission": "2025-06-12T10:00:00",
  "categorie": "TRAVAIL",
  "statut": "EN_ATTENTE"
}

### ExcuseCreative - Création (par PROCRASTINATEUR_EN_HERBE)
POST http://localhost:9000/api/excuse-creative
Content-Type: application/json
X-User-Email: newbie@example.com

{
  "texteExcuse": "Faire un karaoké pour me détendre",
  "situationApp": "Pendant la pause déjeuner",
  "categorie": "ETUDES",
  "statut": "EN_ATTENTE",
  "votesRecus": 0,
  "dateSoumission": "2025-06-01T10:00:00"
}

### ExcuseCreative - Création erreur 400 (données manquantes)
POST http://localhost:9000/api/excuse-creative
Content-Type: application/json
X-User-Email: newbie@example.com

{
"texteExcuse": "",
"categorie": "ETUDES"
}

### ExcuseCreative - Get all
GET http://localhost:9000/api/excuse-creative
Content-Type: application/json
X-User-Email: newbie@example.com

### ExcuseCreative - Get by id
GET http://localhost:9000/api/excuse-creative/1
Content-Type: application/json
X-User-Email: newbie@example.com

### ExcuseCreative - Modification (par PROCRASTINATEUR_REPENTI)
PUT http://localhost:9000/api/excuse-creative/1
Content-Type: application/json
X-User-Email: thebest@example.com

{
  "id": 1,
  "texteExcuse": "Je dois faire du yoga pour me détendre",
  "situationApp": "AVANT de commencer le travail",
  "categorie": "TRAVAIL",
  "statut": "APPROUVEE",
  "votesRecus": 42,
  "dateSoumission": "2025-06-10T15:30:00"
}


### ExcuseCreative -  Modification - erreur 404 (excuse non trouvée
PUT http://localhost:9000/api/excuse-creative/9999
Content-Type: application/json
X-User-Email: thebest@example.com

{
  "texteExcuse": "Excuse modifiée",
  "categorie": "ETUDES",
  "statut": "APPROUVEE",
  "votesRecus": 0,
  "dateSoumission": "2025-06-10T15:30:00"
}

### ExcuseCreative -  Voter une excuse (par PROCRASTINATEUR_EN_HERBE)
POST http://localhost:9000/api/excuse-creative/1/voter?newVote=10
Content-Type: application/json
X-User-Email: newbie@example.com

### ExcuseCreative - Voter - erreur 404 (excuse non trouvée)
POST http://localhost:9000/api/excuse-creative/9999/voter?newVote=77
Content-Type: application/json
X-User-Email: newbie@example.com


### ExcuseCreative - Modération - Cas d’erreur — utilisateur non autorisé
POST http://localhost:9000/api/excuse-creative/1/moderation
Content-Type: application/json
X-User-Email: newbie@example.com


### ExcuseCreative - Suppression erreur 401 (non autorisé)
DELETE http://localhost:9000/api/excuse-creative/1
Content-Type: application/json
X-User-Email: newbie@example.com


### ExcuseCreative - Suppression (par GESTIONNAIRE_TEMPS_PERDU)
DELETE http://localhost:9000/api/excuse-creative/1
Content-Type: application/json
X-User-Email: gestionnaire@example.com

#
# TacheAEviter
#

### TacheAEviter - Création 1 (par PROCRASTINATEUR_EN_HERBE)
POST http://localhost:9000/api/tache-a-eviter
Content-Type: application/json
X-User-Email: newbie@example.com

{
  "description": "Regarder des vidéos inutiles",
  "degreUrgence": 2,
  "dateLimite": "2025-07-01T00:00:00",
  "consequencesPotentielles": "Perte de temps",
  "statut": "EN_ATTENTE",
  "dateCreation": "2025-06-11T09:00:00"
}

### TacheAEviter - Création 2 (par PROCRASTINATEUR_EN_HERBE)
POST http://localhost:9000/api/tache-a-eviter
Content-Type: application/json
X-User-Email: newbie@example.com

{
  "description": "Regarder des séries",
  "degreUrgence": 4,
  "dateLimite": "2025-07-01T00:00:00",
  "consequencesPotentielles": "La procrastination is here to stay",
  "statut": "EN_ATTENTE",
  "dateCreation": "2025-06-01T09:00:00"
}

### TacheAEviter - creation - erreur 400 (date limite invalide)
POST http://localhost:9000/api/tache-a-eviter
Content-Type: application/json
X-User-Email: newbie@example.com

{
  "description": "Tâche invalide",
  "degreUrgence": 5,
  "dateLimite": "2012-12-12T00:00:00",
  "consequencesPotentielles": "FIN DU MONDE",
  "statut": "EN_ATTENTE",
  "dateCreation": "2025-06-05T09:00:00"
}

### TacheAEviter - Get all
GET http://localhost:9000/api/tache-a-eviter
Content-Type: application/json
X-User-Email: newbie@example.com

### TacheAEviter - Get by id
GET http://localhost:9000/api/tache-a-eviter/1
Content-Type: application/json
X-User-Email: newbie@example.com

### TacheAEviter - Modification (par ANTI_PROCRASTINATEUR_REPENTI)
PUT http://localhost:9000/api/tache-a-eviter/1
Content-Type: application/json
X-User-Email: thebest@example.com

{
  "id": 1,
  "description": "Avancer dans le projet",
  "degreUrgence": 3,
  "dateLimite": "2025-07-10T00:00:00",
  "consequencesPotentielles": "Gerer le stress",
  "statut": "CATASTROPHE",
  "dateCreation": "2025-06-01T08:00:00"
}

### TacheAEviter - Modification erreur 404 (tâche non trouvée)
PUT http://localhost:9000/api/tache-a-eviter/999
Content-Type: application/json
X-User-Email: thebest@example.com

{
  "description": "Changer description",
  "degreUrgence": 1,
  "dateLimite": "2025-07-01T00:00:00",
  "consequencesPotentielles": "Perte de temps",
  "statut": "EVITEE_AVEC_SUCCES",
  "dateCreation": "2025-06-01T08:00:00"
}

### TacheAEviter - Modification
PUT http://localhost:9000/api/tache-a-eviter/1
Content-Type: application/json
X-User-Email: thebest@example.com

{
  "description": "Changer description",
  "degreUrgence": 3,
  "dateLimite": "2025-07-01T00:00:00",
  "consequencesPotentielles": "Perte de temps",
  "statut": "EVITEE_AVEC_SUCCES",
  "dateCreation": "2025-06-01T08:00:00"
}

### TacheAEviter -  Recuperer les points d’une tâche
GET http://localhost:9000/api/tache-a-eviter/1/points
Content-Type: application/json
X-User-Email: newbie@example.com

### TacheAEviter -  Recuperer le nb total des points de l’utilisateur
GET http://localhost:9000/api/tache-a-eviter/points/total
Content-Type: application/json
X-User-Email:  newbie@example.com

### TacheAEviter -  Suppression erreur 403 (utilisateur non autorisé)
DELETE http://localhost:9000/api/tache-a-eviter/1
Content-Type: application/json
X-User-Email:  newbie@example.com

### TacheAEviter -  Suppression (par GESTIONNAIRE_TEMPS_PERDU)
DELETE http://localhost:9000/api/tache-a-eviter/1
Content-Type: application/json
X-User-Email: gestionnaire@example.com

### ExcuseCreative - Apres ajout de taches à eviter -  Modération succès (par GESTIONNAIRE_TEMPS_PERDU)
POST http://localhost:9000/api/excuse-creative/3/moderation
Content-Type: application/json
X-User-Email: gestionnaire@example.com

#
# ConfrontationPiege
#

### ConfrontationPiege - Création SUCCES (par PROCRASTINATEUR_EN_HERBE)
POST http://localhost:9000/api/confrontation-pieges
Content-Type: application/json
X-User-Email: newbie@example.com

{ "piege": { "id": 1 }, "dateConfrontation": "2025-06-16", "succes": true, "commentaire": "c'est bien" }

### ConfrontationPiege - Création ECHEC (par PROCRASTINATEUR_EN_HERBE)
POST http://localhost:9000/api/confrontation-pieges
Content-Type: application/json
X-User-Email: newbie@example.com

{ "piege": { "id": 1 }, "dateConfrontation": "2025-06-16", "succes": false, "commentaire": "c'est bien" }

### ConfrontationPiege - Get all (par ANTI_PROCRASTINATEUR_REPENTI)
GET http://localhost:9000/api/confrontation-pieges
Content-Type: application/json
X-User-Email: thebest@example.com

### ConfrontationPiege - Get by id (par PROCRASTINATEUR_EN_HERBE)
GET http://localhost:9000/api/confrontation-pieges/1
Content-Type: application/json
X-User-Email: newbie@example.com

### ConfrontationPiege - Get by piege id (par ANTI_PROCRASTINATEUR_REPENTI)
GET http://localhost:9000/api/confrontation-pieges/piege/1
Content-Type: application/json
X-User-Email: thebest@example.com

### ConfrontationPiege - Get all for connected user (par PROCRASTINATEUR_EN_HERBE)
GET http://localhost:9000/api/confrontation-pieges/user
Content-Type: application/json
X-User-Email: newbie@example.com

### ConfrontationPiege - Suppression (par PROCRASTINATEUR_EN_HERBE)
DELETE http://localhost:9000/api/confrontation-pieges/1
Content-Type: application/json
X-User-Email: newbie@example.com

#
# Autre
#